name: Commit checker

on:
  pull_request:

jobs:
  commit-checker:
    name: Commit checker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 4

    - name: Get pull-request commits
      uses: truebrain/OpenTTD-actions/checkout-pull-request@history-test

    - name: Check commits
      uses: TrueBrain/OpenTTD-git-hooks@make-action
